### ISSUE TITLE
santiellena - Incorrect check of assets decimals in `RioLRTAssetRegistry::_addAsset`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-rio-network-core-protocol-judging#102]
santiellena

medium

# Incorrect check of assets decimals in `RioLRTAssetRegistry::_addAsset`

## Summary
The `_addAsset` function fails to check if asset decimals are in between 6 and 18.
## Vulnerability Detail
In the `RioLRTAssetRegistry::_addAsset` function, if asset decimals are bigger than 18 the function reverts. However, it's lacking of a check to see if decimals are less than 6.

```solidity
    /// @dev Adds a new underlying asset to the liquid restaking token.
    /// @param config The asset's configuration.
    function _addAsset(AssetConfig calldata config) internal {
        if (isSupportedAsset(config.asset)) revert ASSET_ALREADY_SUPPORTED(config.asset);
        if (config.asset == address(0)) revert INVALID_ASSET_ADDRESS();
        
        uint8 decimals = config.asset == ETH_ADDRESS ? 18 : IERC20Metadata(config.asset).decimals();
        if (config.asset == ETH_ADDRESS) {
            if (config.priceFeed != address(0)) revert INVALID_PRICE_FEED();
            if (config.strategy != BEACON_CHAIN_STRATEGY) revert INVALID_STRATEGY();
        } else {
            if (decimals > 18) revert INVALID_ASSET_DECIMALS(); // @audit HERE!!
            if (config.priceFeed == address(0)) revert INVALID_PRICE_FEED();
            if (IPriceFeed(config.priceFeed).decimals() != priceFeedDecimals) revert INVALID_PRICE_FEED_DECIMALS();
            if (IStrategy(config.strategy).underlyingToken() != config.asset) revert INVALID_STRATEGY();
        }
        supportedAssets.push(config.asset);
        
        AssetInfo storage info = assetInfo[config.asset];
        info.decimals = decimals;
        info.depositCap = config.depositCap;
        info.priceFeed = config.priceFeed;
        info.strategy = config.strategy;
        
        emit AssetAdded(config);
    }
```

Audit README.md clearly states:

```markdown
### Q: Do you expect to use any of the following tokens with non-standard behaviour with the smart contracts?
- We plan to support tokens with no less than 6 decimals and no more than 18 decimals.
```
## Impact
In addition to the unexpected behavior, the protocol and users could suffer from precision loss which leads to big percentage losses.
## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTAssetRegistry.sol#L324-L349
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/README.md?plain=1#L75-L76
## Tool used

Manual Review

## Recommendation
Check if asset decimals are no less than 6 decimals and no more than 18 decimals:

```diff
- if (decimals > 18) revert INVALID_ASSET_DECIMALS();
+ if (6 > decimals > 18) revert INVALID_ASSET_DECIMALS();
```

Duplicate of #168

**Comment by solimander** [comment]
We are not planning to support any underlying assets with less than 6 decimals, but this is not someone that we plan to enforce onchain.
