### ISSUE TITLE
almurhasan - Rebalance will revert when the address pool has less balance than the epoch’s shareowed.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-rio-network-core-protocol-judging#179]
almurhasan

high

# Rebalance will revert when the address pool has less balance than the epoch’s shareowed.

## Summary
Rebalance settles an epoch when the address pool has more balance than the current epoch’s shareowed for an asset. If the address pool has less balance, then the remaining balance are withdrawn from eigenlayer , but this will not work properly

## Vulnerability Detail
1. Let assume for an asset, total shareowed = 10k for withdrawals and total address pool balance = 8k in the current epoch.
2. The rebalance function is called,  as  sharesOwed >0, _processUserWithdrawalsForCurrentEpoch function is called where, as deposit pool has 8k balance , so deposit pool sends total 8k balance to the  withdrawalQueue. Now the deposit pool has 0 balance for this asset.
3. As sharesRemaining>0,the epoch does not settle and this creates queueCurrentEpochSettlement.
4. See rebalance function , after the above process, remaining asset’s balance(which is 0) are deposited to eigenlayer from the deposit pool. As the deposit pool has 0 asset’s balance, so sharesReceived = 0.
5. As sharesReceived = 0, this causes a revert of the rebalance function.
## Impact
Rebalance will not work properly.

## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L133
## Tool used

Manual Review

## Recommendation
Remove sharesReceived = 0 from the if statement.

Duplicate of #18

**Comment by Almur100** [comment]
This is different from issue 18. This is valid issue.

**Comment by Almur100** [comment]
This issue is different from issue 18. This is a valid issue

**Comment by Almur100** [comment]
This is a valid high issue

**Comment by Almur100** [comment]
nevillehuang, this is not a feature

**Comment by Almur100** [comment]
solimander, this is valid issue
