### ISSUE TITLE
itsabinashb - RioLRTCore::No storage gap implementation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-rio-network-core-protocol-judging#24]
itsabinashb

medium

# RioLRTCore::No storage gap implementation

## Summary
No storage gap was used by RioLRTCore.sol contract for future upgrade.
## Vulnerability Detail
The RioLRTCore.sol contract does not contain any storage gap. Many contracts in this system is inherited from RioLRTCore contract for ex- RioAssetRegistry, RioLRTAVSRegistry, RioLRTCoordinator, RioLRTDepositPool, RioLRTOperatorDelegator and few more. So if in future upgrade any storage variable is added in RioLRTCore contract it will overwrite the storage variable of any one of the inherited contract.
## Impact
See Vulnerability detail section.
## Code Snippet
1. https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTAVSRegistry.sol#L9
2. https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTAssetRegistry.sol#L15
3. https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L17
## Tool used

Manual Review

## Recommendation
Use:
```solidity
uint256[100] private __gap;
```

Duplicate of #346

**Comment by solimander** [comment]
This is for address calculation only. No new storage slots will be used in the future.
