### ISSUE TITLE
Topmark - Incomplete Implementation of Operator Removal in the OperatorUtilizationHeap.sol contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-rio-network-core-protocol-judging#30]
Topmark

medium

# Incomplete Implementation of Operator Removal in the OperatorUtilizationHeap.sol contract

## Summary
Incomplete Implementation of Operator Removal in the OperatorUtilizationHeap.sol contract as against comment description.
## Vulnerability Detail
```solidity
>>> /// @dev Removes the operator at the specified index from the heap by
    /// swapping it with the last operator in the heap.
    /// @param self The heap.
    /// @param i The index of the operator to extract.
   function _remove(Data memory self, uint8 i) internal pure {
>>>        self.operators[i] = self.operators[self.count--];
    }
```
The code above shows how Operator Removal is implemented in the OperatorUtilizationHeap.sol contract, as noted from the comment description a complete removal of operator should be done, however only reassignment and reduction of self.count was done which means the unwanted operator data would still exist in the mapping which could misrepresent the Operator data information in the contract
## Impact
Incomplete Implementation of Operator Removal in the OperatorUtilizationHeap.sol contract as against comment description.
## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/utils/OperatorUtilizationHeap.sol#L389
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/utils/OperatorRegistryV1Admin.sol#L253
## Tool used

Manual Review

## Recommendation
The Operator that is no longer needed should be completely deleted in the _remove(...) function of the OperatorUtilizationHeap contract

**Comment by Topmark1** [comment]
@nevillehuang There is no different in the report from https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/155 Judge should please reconsider, thanks
