### ISSUE TITLE
hash - Withdrawals close to maximum amount can revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-rio-network-core-protocol-judging#301]
hash

medium

# Withdrawals close to maximum amount can revert

## Summary
Rebalance can revert when close to maximum available amount of shares is withdrawn as the balance in deposit pool may not cover its portion of owed shares

## Vulnerability Detail
Withdrawals are settled using funds from the depositPool and the earlier acquired shares in EigenLayer. To calculate how much shares is withdrawable, the depositPool token balance is converted to its corresponding share balance using the current exchange rate from EigenLayer. If the shares acquired from previous deposits were `x` and the deposit pool token balance corresponds to `y` shares using the current exchange rate, user's are allowed to request withdrawals for upto `x+y` shares. 
After the withdrawal request from the user, it can take upto rebalance delay ~24hrs amount of time to actually execute the withdrawal. In case the total requested withdrawal amount was close to the maximum amount of withdrawable assets and the exchange rate in EigenLayer changes (one share is worth more now. and hence the `y` amount of shares is now worth more the deposit pool token balance), the rebalance call will revert since the transfer of deposit pool token balance will not cover its associated portion of shares (unless further deposits are made) and there won't be enough shares to withdraw from EigenLayer.    

## Impact
Rebalance and hence withdrawals can revert when close to maximum available amount of shares is withdrawn

## Code Snippet
withdrawal requests consider the current exchange rate from eigenlayer to convert deposit pool balance
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L99-L114

the transfer from deposit pool is supposed to cover its portion of shares in the total shares owed
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/4f01e065c1ed346875cf5b05d2b43e0bcdb4c849/rio-sherlock-audit/contracts/restaking/RioLRTCoordinator.sol#L245-L252

## Tool used
Manual Review

## Recommendation
Since this will happen rarely it could be managed by monitoring for this case and making necessary deposits

Duplicate of #361

**Comment by zzykxx** [comment]
Escalate

I believe this issue is a duplicate of #109: "In case the total requested withdrawal amount was close to the maximum amount of withdrawable assets **and the exchange rate in EigenLayer changes** the rebalance call will revert ".

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I believe this issue is a duplicate of #109: "In case the total requested withdrawal amount was close to the maximum amount of withdrawable assets **and the exchange rate in EigenLayer changes** the rebalance call will revert ".
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@zzykxx Agree should be duplicate of #109

**Comment by Czar102** [comment]
In that case, planning to accept the escalation and make this a duplicate of #109 instead of #5.

**Comment by Czar102** [comment]
Result:
Medium
Duplicate of #109

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zzykxx](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/301/#issuecomment-2024510573): accepted

**Comment by Czar102** [comment]
Making it a duplicate of #361 since the majority of that family is deduplicated there and this finding doesn't mention donations.
