### ISSUE TITLE
giraffe - Hardcoded `receiveAsTokens = true` could lead to stuck funds in strategy

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-rio-network-core-protocol-judging#57]
giraffe

high

# Hardcoded `receiveAsTokens = true` could lead to stuck funds in strategy

## Summary
During the completion of a withdraw process on Eigenlayer, if a strategy contract reverts then funds cannot be withdrawn. A workaround exists which is to call Eigenlayer contracts with `receiveAsToken = false`. However, due to hardcoded values in Rio, this workaround is not available leading to stuck/loss of funds.

## Vulnerability Detail
Completing a withdrawal on Rio takes place in two areas: 1) RioLRTWithdrawalQueue.sol `settleEpochFromEigenLayer()` and 2) RiolLRTDepositPool.sol `completeOperatorWithdrawalForAsset()`. In both functions, the parameter `receiveAsTokens` is set to `true`, indicating the intention to receive withdrawals in tokens instead of shares.
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTWithdrawalQueue.sol#L252
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTDepositPool.sol#L144
```solidity
delegationManager.completeQueuedWithdrawal(queuedWithdrawal, asset.toArray(), middlewareTimesIndex, true); //@audit receiveAsTokens set to true
```

When Eigenlayer executes`completeQueuedWithdrawal()`, the `withdraw` function of the strategy contract is called (if `receiveAsTokens` is set to true). https://github.com/Layr-Labs/eigenlayer-contracts/blob/v0.2.1-goerli-m2/src/contracts/core/StrategyManager.sol#L189C5-L196C6
```solidity
function withdrawSharesAsTokens(
        address recipient,
        IStrategy strategy,
        uint256 shares,
        IERC20 token
    ) external onlyDelegationManager {
        strategy.withdraw(recipient, token, shares);
    }
```

However, the strategy contract could revert due to a variety of reasons including: a) contract is malicious, or b) contract has insufficient liquidity,  or c) contract is paused, or d) contract has a bug. Eigenlayer takes this possibility into consideration as seen [here](https://github.com/code-423n4/2023-04-eigenlayer/blob/main/src/contracts/core/StrategyManager.sol#L533-L534).

A workaround to this would be to call `completeQueuedWithdrawal()` again with `receiveAsTokens` set to `false`. This allows the caller to receive the withdrawal as shares in `DelegationManager.sol`. Caller can then go on to queue a new withdrawal from a different strategy to receive the withdrawal as tokens. This workaround was discussed in a previous Eigenlayer audit found [here](https://github.com/code-423n4/2023-04-eigenlayer-findings/issues/132).

The prescribed workaround however is not possible in Rio's contracts as the `receiveAsTokens` parameter is hardcoded to `true`.
## Impact
User and protocol funds may end up permanently stuck in a strategy.

## Code Snippet
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTWithdrawalQueue.sol#L252
https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTDepositPool.sol#L144

## Tool used
Manual Review

## Recommendation
Allowing the `receiveAsTokens` parameter to be input as `false` will require significant re-design of Rio's contracts to handle such scenarios. So instead, protocol could consider adding emergency functions that can complete withdrawals with `receiveAsTokens = false` and direct the receiving tokens to either the deposit pool or withdraw queue.  

Duplicate of #247

**Comment by giraffe0x** [comment]
Escalate.

Not a duplicate to #247 (doesn't seem similar, unrelated to pausing).

I understand that "risks associated with EigenLayer and EigenLayer's governance are considered acceptable." My point is that Eigenlayer has accepted a risk that external strategy contracts may be malicious (see [here](https://github.com/code-423n4/2023-04-eigenlayer/blob/main/src/contracts/core/StrategyManager.sol#L533-L534) and therefore provided a solution to prevent DOS through the use of `receiveAsTokens = false` 

However, by hardcoding `receiveAsTokens = true`, Rio network is unable to make use of the alternative solution.

**Comment by nevillehuang** [comment]
This issue to me is purely speculation, and I duplicated it because I believe it falls under the acceptable risks below. Not supporting a workaround is not a security risk.

> Yes, the risks associated with EigenLayer and EigenLayer's governance are considered acceptable.

**Comment by giraffe0x** [comment]
The security risk here is possible DOS and stuck funds. 

This was also a valid medium finding in the [Eigen C4 contest](https://github.com/code-423n4/2023-04-eigenlayer-findings/issues/132#issuecomment-1575599410). It established that:
1) Several scenarios, including that of a malicious strategy contract could cause the DOS
2) But, even if a malicious strategy exists, there is no permanent delay here as users can mark the `receiveAsTokens` input to `completeQueuedWithdrawal` as `false`.

My finding is that the second point is not available to Rio because it hardcodes the param to `true`. So in the event that there is a malicious strategy then Rio's users funds will be stuck.

**Comment by nevillehuang** [comment]
I think this should be considered in the context of rio, not eigen layer as in the C4 contest. As you mentioned, As far as I know, risks associated with eigenlayer governance is accepted, and since this is a workaround revolving those actions, should be invalid. Will loop in sponsor for comments nevertheless

**Comment by solimander** [comment]
This is an accepted risk of EigenLayer. The diligence process will prevent malicious strategies from being included, and a bug in an included strategy could require a contract upgrade, but I agree with @nevillehuang - seems like speculation.

**Comment by Czar102** [comment]
I agree, this seems to be a low severity finding. Planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Low
Duplicate of #247

(duplication status doesn't matter as it's not going to be rewarded)

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [giraffe0x](https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/57/#issuecomment-2019977189): rejected
