### ISSUE TITLE
boredpukar - Fixed Amount of Gas Sent in Call May Be Insufficient.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-02-rio-network-core-protocol-judging#8]
boredpukar

medium

# Fixed Amount of Gas Sent in Call May Be Insufficient.

## Summary

The `Asset::transferETH` makes a call with a fixed amount of gas, 10,000. If the receiver is a contract this may be insufficient to process the receive() function. As a result the user would be unable to receive funds from this function.

## Vulnerability Detail

The transferETH function sets a gas limit of 10,000 for the ETH transfer. This is generally a good practice to prevent reentrancy attacks. However, this might not be sufficient for all contracts to perform operations, which could lead to failed transactions when sending to contracts expecting to perform such operations.

## Impact

The function uses a low-level call with a fixed gas limit of 10,000 to send ETH. While setting a fixed gas limit can prevent the contract from spending too much gas, it might not be sufficient for all contract interactions that require more than 10,000 gas, leading to potential failures in ETH transfers.

Consideration of the gas limit is crucial, especially with EIP-1884 which adjusted the cost of certain opcodes and could affect contracts relying on hardcoded gas amounts.

## Code Snippet

```solidity
    /// @audit - ETH transfer with a hardcoded gas value
    /// @dev Sends `amount` of ETH to `recipient`.
    /// @param recipient The asset recipient.
    /// @param amount The amount of ETH to send.
    /// @dev This function limits the gas passed with the call to 10,000.
    function transferETH(address recipient, uint256 amount) internal {
        (bool success,) = recipient.call{value: amount, gas: 10_000}('');
        if (!success) {
            revert ETH_TRANSFER_FAILED();
        }
    }
```

https://github.com/sherlock-audit/2024-02-rio-vesting-core-protocol/blob/main/rio-sherlock-audit/contracts/utils/Asset.sol#L42

## Tool used

Manual Review

## Recommendation

Allow for a more flexible gas limit or implement error handling that can better accommodate the variable gas requirements of different contracts.

An ideal solution could be something similar to below implementation.
```solidity
    /// @dev Attempts to send `amount` of ETH to `recipient` with fallback on failure.
    /// @param recipient The asset recipient.
    /// @param amount The amount of ETH to send.
    function transferETH(address recipient, uint256 amount) public {
        // Attempt with a reasonable fixed gas limit
        try this.transferWithFixedGas(recipient, amount, 10000) {
            // Transfer succeeded
        } catch {
            // Fallback mechanism or alternative action
            // Could involve a different gas limit, logging, or other recovery actions
        }
    }

    /// @dev Internal function to perform the transfer with a specific gas limit.
    /// @notice This function is marked as external to be used with try-catch.
    /// @param recipient The asset recipient.
    /// @param amount The amount of ETH to send.
    /// @param gasLimit The gas limit for the call.
    function transferWithFixedGas(address recipient, uint256 amount, uint256 gasLimit) external {
        require(msg.sender == address(this), "Only callable internally");
        (bool success,) = recipient.call{value: amount, gas: gasLimit}("");
        if (!success) {
            revert("ETH_TRANSFER_FAILED");
        }
    }
```

Duplicate of #185

**Comment by solimander** [comment]
Not as worried about the gas limitation when withdrawing, but will fix in: https://github.com/sherlock-audit/2024-02-rio-network-core-protocol-judging/issues/87
