### ISSUE TITLE
0xkaden - Operators can arbitrarily modify their operatorDetails after RioLRTOperatorDelegator initialization

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-rio-network-core-protocol-judging#88]
0xkaden

high

# Operators can arbitrarily modify their operatorDetails after RioLRTOperatorDelegator initialization

## Summary

Validation is done on operatorDetails, in particular to ensure that rewards are distributed correctly. However, operators can arbitrarily modify their operatorDetails such that rewards are distributed to themselves.

## Vulnerability Detail

In RioLRTOperatorDelegator.initialize, the operator details are validated to confirm to certain expectations or else initialization reverts:

```solidity
IDelegationManager.OperatorDetails memory operatorDetails = delegationManager.operatorDetails(operator);
if (operatorDetails.earningsReceiver != address(rewardDistributor())) revert INVALID_EARNINGS_RECEIVER();
if (operatorDetails.delegationApprover != address(0)) revert INVALID_DELEGATION_APPROVER();
if (operatorDetails.stakerOptOutWindowBlocks < operatorRegistry().minStakerOptOutBlocks()) {
    revert INVALID_STAKER_OPT_OUT_BLOCKS();
}
```

Most notably, the earningsReceiver must be set as the rewardDistributor. As noted by the sponsor, this is so that when EigenLayer enables payments they will be properly distributed.

The problem is that operators can arbitrarily modify any of these details at any time with DelegationManager.modifyOperatorDetails:

```solidity
function modifyOperatorDetails(OperatorDetails calldata newOperatorDetails) external {
    require(isOperator(msg.sender), "DelegationManager.modifyOperatorDetails: caller must be an operator");
    _setOperatorDetails(msg.sender, newOperatorDetails);
}

...

function _setOperatorDetails(address operator, OperatorDetails calldata newOperatorDetails) internal {
    require(
        newOperatorDetails.earningsReceiver != address(0),
        "DelegationManager._setOperatorDetails: cannot set `earningsReceiver` to zero address"
    );
    require(
        newOperatorDetails.stakerOptOutWindowBlocks <= MAX_STAKER_OPT_OUT_WINDOW_BLOCKS,
        "DelegationManager._setOperatorDetails: stakerOptOutWindowBlocks cannot be > MAX_STAKER_OPT_OUT_WINDOW_BLOCKS"
    );
    require(
        newOperatorDetails.stakerOptOutWindowBlocks >= _operatorDetails[operator].stakerOptOutWindowBlocks,
        "DelegationManager._setOperatorDetails: stakerOptOutWindowBlocks cannot be decreased"
    );
    _operatorDetails[operator] = newOperatorDetails;
    emit OperatorDetailsModified(msg.sender, newOperatorDetails);
}
```

## Impact

Operators can steal rewards by setting their own address as the earningsReceiver at any time.

## Code Snippet

https://github.com/sherlock-audit/2024-02-rio-network-core-protocol/blob/main/rio-sherlock-audit/contracts/restaking/RioLRTOperatorDelegator.sol#L81

## Tool used

Manual Review

## Recommendation

It's unclear how to solve this considering the logic is baked into EigenLayer. Perhaps consider a mechanism for incentivizing honesty of operators, e.g. slashing.

Duplicate of #196

**Comment by solimander** [comment]
Invalid - We cannot enforce this onchain. Operators are trusted partners, but they will be removed from the active set if they fail to update their earnings receiver.
